### ISSUE TITLE
Jsonnet error when unrolling policy

### ISSUE THREAD

**Issue by vonHartz** [openai/multi-agent-emergence-environments#21]
Hi,

I created a fresh python 3.6 environments and installed the dependencies from both repositories. However, when I try to unroll a saved policy in the respective environment, e.g. `$ bin/examine.py examples/hide_and_seek_quadrant.jsonnet examples/hide_and_seek_quadrant.npz`, I get  `RuntimeError: STATIC ERROR: std.jsonnet:1249:1-5: did not expect: (IDENTIFIER, "core")`.

This might or might not be related to #19, as I am experiencing that problem as well.

Here's the full stack:
```$ bin/examine.py examples/hide_and_seek_full.jsonnet examples/hide_and_seek_full.npz 

Inferred:
	names: examples/hide_and_seek_full.jsonnet examples/hide_and_seek_full.npz
	arguments: {}


/home/jan/.conda/envs/openairl/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jan/.conda/envs/openairl/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jan/.conda/envs/openairl/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jan/.conda/envs/openairl/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/jan/.conda/envs/openairl/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/jan/.conda/envs/openairl/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "bin/examine.py", line 91, in <module>
    main()
  File "/home/jan/.conda/envs/openairl/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jan/.conda/envs/openairl/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jan/.conda/envs/openairl/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jan/.conda/envs/openairl/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "bin/examine.py", line 58, in main
    return_args_remaining=True, **kwargs)
  File "/home/jan/Projekte/PsychoRL/mujoco-worldgen/mujoco_worldgen/util/envs/flexible_load.py", line 81, in load_env
    env_data = json.loads(_jsonnet.evaluate_file(pattern))
RuntimeError: STATIC ERROR: std.jsonnet:1249:1-5: did not expect: (IDENTIFIER, "core")
```

**Comment by Dilhiadxan** [comment]
What do you want from me?

вт, 14 апр. 2020 г. в 21:45, Jan Ole v. Hartz <notifications@github.com>:

**Comment by vonHartz** [comment]
Apparently, this was an issue with jsonnet 0.11.2, see [jsonnet issue](https://github.com/google/jsonnet/issues/568). Manually upgrading `pip install --upgrade jsonnet`solves the issue.

I'll close this one and open an issue at https://github.com/openai/mujoco-worldgen to fix the requirements.
