### ISSUE TITLE
Error when loading pre-trained policy

### ISSUE THREAD

**Issue by DebasmitaGhose** [openai/multi-agent-emergence-environments#48]
When I examine the environment using the command `bin/examine.py examples/hide_and_seek_quadrant.jsonnet examples/hide_and_seek_quadrant.npz`, I get the error below. However, when I do not specify the `.npz` file, I am able to successfully visualize the environment. 

```
(mujoco) scazlab@scazlab-INTEL:~/catkin_ws/src/multi-agent-emergence-environments$ bin/examine.py examples/hide_and_seek_quadrant.jsonnet examples/hide_and_seek_quadrant.npz

Inferred:
	names: examples/hide_and_seek_quadrant.jsonnet examples/hide_and_seek_quadrant.npz
	arguments: {}


2022-12-05 17:46:48.707354: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-05 17:46:48.796426: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-12-05 17:46:49.134219: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/scazlab/catkin_ws/devel/lib:/opt/ros/melodic/lib:/usr/local/cuda/lib64:/home/scazlab/.mujoco/mujoco210/bin:/usr/lib/nvidia
2022-12-05 17:46:49.134264: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/scazlab/catkin_ws/devel/lib:/opt/ros/melodic/lib:/usr/local/cuda/lib64:/home/scazlab/.mujoco/mujoco210/bin:/usr/lib/nvidia
2022-12-05 17:46:49.134269: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/scazlab/catkin_ws/src/multi-agent-emergence-environments/bin/examine.py", line 91, in <module>
    main()
  File "/home/scazlab/anaconda3/envs/mujoco/lib/python3.10/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/scazlab/anaconda3/envs/mujoco/lib/python3.10/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/scazlab/anaconda3/envs/mujoco/lib/python3.10/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/scazlab/anaconda3/envs/mujoco/lib/python3.10/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/scazlab/catkin_ws/src/multi-agent-emergence-environments/bin/examine.py", line 54, in main
    from ma_policy.load_policy import load_policy
  File "/home/scazlab/catkin_ws/src/multi-agent-emergence-environments/ma_policy/load_policy.py", line 7, in <module>
    import cloudpickle as pickle
  File "/home/scazlab/anaconda3/envs/mujoco/lib/python3.10/site-packages/cloudpickle/__init__.py", line 3, in <module>
    from cloudpickle.cloudpickle import *
  File "/home/scazlab/anaconda3/envs/mujoco/lib/python3.10/site-packages/cloudpickle/cloudpickle.py", line 151, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/home/scazlab/anaconda3/envs/mujoco/lib/python3.10/site-packages/cloudpickle/cloudpickle.py", line 132, in _make_cell_set_template_code
    return types.CodeType(
```

**Comment by Pixelspi73** [comment]
Thank you
