### ISSUE TITLE
Running example environment: invalid scope name

### ISSUE THREAD

**Issue by AnandS29** [openai/multi-agent-emergence-environments#6]
Hi, I'm trying to run the example environment as specified in the doc: `bin/examine.py examples/hide_and_seek_quadrant.jsonnet examples/hide_and_seek_quadrant.npz`. I've installed all the dependencies without issue. I'm not exactly sure what problem is, and I get the following output when I try running the above command:

```
`(rl_env)  :multi-agent-emergence-environments  $ bin/examine.py examples/hide_and_seek_quadrant.jsonnet examples/hide_and_seek_quadrant.npz
objc[68761]: Class GLFWApplicationDelegate is implemented in both /Users/ /.mujoco/mjpro150/bin/libglfw.3.dylib (0x10c9de778) and /usr/local/Cellar/glfw/3.3/lib/libglfw.3.3.dylib (0x10cb26710). One of the two will be used. Which one is undefined.
objc[68761]: Class GLFWWindowDelegate is implemented in both /Users/*****/.mujoco/mjpro150/bin/libglfw.3.dylib (0x10c9de700) and /usr/local/Cellar/glfw/3.3/lib/libglfw.3.3.dylib (0x10cb26738). One of the two will be used. Which one is undefined.
objc[68761]: Class GLFWContentView is implemented in both /Users/*****/.mujoco/mjpro150/bin/libglfw.3.dylib (0x10c9de7a0) and /usr/local/Cellar/glfw/3.3/lib/libglfw.3.3.dylib (0x10cb26788). One of the two will be used. Which one is undefined.
objc[68761]: Class GLFWWindow is implemented in both /Users/*****/.mujoco/mjpro150/bin/libglfw.3.dylib (0x10c9de818) and /usr/local/Cellar/glfw/3.3/lib/libglfw.3.3.dylib (0x10cb26800). One of the two will be used. Which one is undefined.

Inferred:
	names: examples/hide_and_seek_quadrant.jsonnet examples/hide_and_seek_quadrant.npz
	arguments: {}


WARN: <class 'mae_envs.envs.hide_and_seek.HideAndSeekRewardWrapper'> doesn't implement 'reset' method, which is required for wrappers derived directly from Wrapper. Deprecated default implementation is used.
2019-09-21 15:52:25.117396: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "bin/examine.py", line 91, in <module>
    main()
  File "//anaconda3/envs/rl_env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "//anaconda3/envs/rl_env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "//anaconda3/envs/rl_env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "//anaconda3/envs/rl_env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "bin/examine.py", line 68, in main
    for i, name in enumerate(policy_names)]
  File "bin/examine.py", line 68, in <listcomp>
    for i, name in enumerate(policy_names)]
  File "/Users/*****/Desktop/rl/multi-agent-emergence-environments/ma_policy/load_policy.py", line 73, in load_policy
    policy = MAPolicy(**policy_args)
  File "/Users/*****/Desktop/rl/multi-agent-emergence-environments/ma_policy/ma_policy.py", line 88, in __init__
    with tf.variable_scope(self.scope, reuse=self.reuse):
  File "//anaconda3/envs/rl_env/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1980, in __enter__
    return self._enter_scope_uncached()
  File "//anaconda3/envs/rl_env/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2024, in _enter_scope_uncached
    current_name_scope_name = current_name_scope.__enter__()
  File "//anaconda3/envs/rl_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 6008, in __enter__
    return self._name_scope.__enter__()
  File "//anaconda3/envs/rl_env/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "//anaconda3/envs/rl_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 4131, in name_scope
    raise ValueError("'%s' is not a valid scope name" % name)
ValueError: 'policy_{i}' is not a valid scope name
`
```

**Comment by AnandS29** [comment]
Fixed this naively by doing 
```
policies = [load_policy(name, env=env, scope='policy_'+str(i))
                    for i, name in enumerate(policy_names)]
```.
